version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

# NOTE:
# Pinned to v4 due to use of cloudflare_zone_settings_override.
# v5 migration requires resource replacement + state migration.
# version = "~> 4.52"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "cloudflare/cloudflare"
        update-types: ["version-update:semver-major"]
